### PR TITLE
Ports to cmake

### PR DESCRIPTION
**Pull request by fran6co**
Uses cmake instead of makefiles. Advatanges:
- Ability to generate IDEs project files
- Automatic and standard binary folder management and temporary folders (obj folder, hex files)
- Bases for creating automated tests (ctest)

### CODE REVIEW

**Comment by fran6co** [comment]
Rebased

**Comment by fran6co** [comment]
@maazl why don't you prefer cmake?

**Comment by maazl** [comment]
On 14.03.16 17.21, Francisco Facioni wrote:

> @maazl https://github.com/maazl why don't you prefer cmake?

Well, I simply did not yet get time to get used to cmake. This does not 
mean that switching to cmake is a bad idea. In fact it is on my TODO list.
But I will only switch the vc4asm build. The test applications cannot 
run on anything else but a Raspberry Pi with Linux anyway. So 
portability is not an issue there.

By the way, your patch to the makefile should not be necessary, because 
I simply disinfected WriteELF.\* by #ifdef. The empty files should not 
cause any harm on MacOS.

And the other patch to the test applications. Well, since they can only 
run with Linux it should not harm either. At least it is a problem of 
the hello_fft template from the Raspberry Foundation too.

In fact I will replace the entire mailbox code at some time. I am 
planning a libgpufft library together with the vcio2 kernel device that 
does not require root privileges to run. However, again a point in the TODO.

Currently I am working on a different FFT implementation which requires 
less memory I/O, significantly higher precision and seem to operate 
about 30% faster.

**Comment by fran6co** [comment]
Great! Removed the other PR about ELF and patched the formula to use your commit (until next release at least). I'll keep this PR open and updated then.
Awesome about the new FFT implementation!

**Comment by maazl** [comment]
I tried to switch to cmake now. Unfortunately cmake seems not to be very well suited for cross platform development and slow devices. I fumbled around half a day but I hit some snags.

First of all build time on the RPi is significantly increased because all common dependencies of vc4asm and vc4dis are compiled twice. - No big deal on a normal computer but in the order of two extra minutes for a Pi 1. :-(
The reason is that the path for the intermediate files contains the target name. This seems to be hard coded into cmake. At least I did not manage to configure this via CMakeList.txt.

Another drawback is that once cmake has run on a platform the build directory is poisoned by the CMakeCache.txt file. If I run cmake from another platform I always get an error until I delete CMakeCache.txt manually. Again the path for this file seems to be hard coded into cmake.
This happens quite often because for debugging I usually compile and run at the development host while I need to run on the Pi to test the generated GPU code. With the invariant Makefile this was much easier.
My hope was that with cmake I could define platform dependent build and binary directories (that's easy) and compile for both platforms in one source folder without the need for full rebuilds on changes. But it does not work because of the cache file. :-(

The first issue is almost a stopper for me.
As compromise I could add the CMakeList.txt file additionally. If I use a different folder, e.g. the project root, it would not collide with the Makefile in the src directory.

P.S. the new FFT memory layout turns out to be much more complicated than expected.

**Comment by fran6co** [comment]
I moved away from GPU programming for the Raspberry Pi at the moment and I'm not sure if I'll ever come back to it. I'm sure that the duplicated compilation can be fixed, but not sure if I'll have the time to check it out.
Regarding the cache what you can do is to have 2 build folders instead, just create a `build_host` and a `build_pi` and run `cmake ..` from them in the corresponding platform.

**Comment by fran6co** [comment]
Well, I actually had some minutes to spare so I decided to fix this PR:

- Fixed the duplicated compilation
- Rebased and updated to the latest changes
- Tested the multiple build folders and it works fine, that should avoid clearing the cache everytime you change platforms, you would only need to change folders

**Comment by maazl** [comment]
Switching to CMake has completed.

**Pull request closed without merging**
