### PR TITLE
Added building as library (shared and static)

### PR DESCRIPTION
**Pull request by doe300**
This extends the Makefile to build the vc4asm as shared and static library into the lib/ folder to be used in other projects

### CODE REVIEW

**Comment by maazl** [comment]
I am still working on the cmake migration, so the library has to be ported to cmake as well. However, the change should not cause much harm.

Unfortunately some hard coded properties of cmake make it really hard to build partially cross platform from the same source directory, i.e. the assembler can build on any platform while the sample binaries are in fact restricted to Raspberry Pi, which in fact are three platforms for now (ARMV6, ARMV7 and ARM64).

**Comment by doe300** [comment]
A cmake build-script would be great.

Could'n you just add a check to cmake, so the sample-binaries are only built, if the architecture is a Raspberry Pi (or the code is built with a Raspberry Pi cross-compiler)?

**Comment by maazl** [comment]
On 18.03.17 09.55, doe300 wrote:
> A cmake build-script would be great.
>
> Could'n you just add a check to cmake, so the sample-binaries are only
> built, if the architecture is a Raspberry Pi (or the code is built with
> a Raspberry Pi cross-compiler)?

This is not the main problem. - Although I have no idea how to identify 
all flavors of Pi and cross compilation reliably.

If you want to do debugging vc4asm it is not just about cross 
compilation. In this case I prefer to run vc4asm on more powerful 
hardware. But at this point the changes are not yet committed to git. So 
the source tree needs to be the same than for the native ARM builds. 
Otherwise I would need two source trees and a topic branch for really 
every change.

I ended up to rape cmake until it creates the output and any cache files 
in a build folder named 
"build-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}-${CMAKE_BUILD_TYPE}".
Unfortunately this raises the next problem that the example builds need 
to refer to the matching binaries. While this is straight forward for 
the first two variables it is not for the second one, since there is no 
need to use the debug build of vc4asm to build a debug version of the 
samples. But debug and release cannot use the same build folder either 
because cmake simply cannot handle this with its cache file.
Furthermore this breaks cross compilation because now the cross 
compilation of the samples require a build with _local_ platform of 
vc4asm even if we are cross compiling. I have no idea how to get cmake 
to do this job.

**Comment by ilovezfs** [comment]
The changes made here have broken the build on macOS. See https://github.com/maazl/vc4asm/issues/18.

**Pull request merged**
